### ISSUE TITLE
Is AddressBook IoC container similar?

### ISSUE THREAD

**Issue by varghesep** [Horusiath/AkkaCQRS#6]
Is **AddressBook** equivalent to an **IoC Container** where singleton instances of coordinators and routers are managed?

**Comment by Horusiath** [comment]
In current example it's role is similar to IoC - to keep access points (in form of the `IActorRef`s) to all major services in the program, and return them on demand. But it isn't responsible for creating them.

Similar properties (registering, unregistering and resolving services) are also common to service discovery patterns - I think that treating address book like a local version of service discovery is better mental model. Since it's an actor and it's aware of it's purpose it may provide additional features, for example tracking and unregistering dead actors.
